services:
  postgre:
    container_name: db_kubenews
    image: postgres:${POSTGRES_TAG}
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net
  web:
    extends:
      file: ./kube-news.compose.yaml
      service: kube_news
volumes:
  docker_vol:
    name: postgre_kubenews

networks:
  kube_news_net:
    driver: bridge