apiVersion: v1
kind: LimitRange
metadata:
  name: valor-padrao
spec:
  limits:
    - type: Container
      default: # Resource Limit
        cpu: 500m
        memory: 64M
      defaultRequest: # Resource Request
        cpu: 250m
        memory: 32M